---
- hosts: localhost
  vars:
     automatic_reboot: false
     perform_updates: true
     update_ansible_core: true
     #Safe package list (all packages in the bundle)
     #excluded_package_list: "ansible-2*, ansible-tower*, bubblewrap*, erlang*, libtomcrypt*, lobtommath*, lyx-fonts*, 1:nginx*, postgresql96*, python-meld3*, python-psycopg2*, python2-crypto*, python2-ecdsa*, python2-paramiko*, python2-psutil*, rabbitmq*, sshpass*, supervisor*"
     #Short package list
     excluded_package_list: "ansible-tower*, rabbit*, python*, postgresql96*"
     
  tasks:
  - name: "Install yum-utils if not already present"
    yum:
      name: yum-utils
      state: latest

  #For extra safety, the excluded package list will be versionlocked using the yum plugin
  #This will prevent extra issues if a manual yum update is run in the future
  - name: "Install yum-plugin-versionlock"
    yum:
      name: yum-plugin-versionlock
      state: latest

  - name: "Add tower packages to versionlock"
    command: "yum versionlock {{ excluded_package_list }}"

  - name: "Updating ansible core"
    yum: 
      name: ansible
      state: latest
    when: ( update_ansible_core == true ) and ( perform_updates == true )

  - name: "Update all packages excluding specific ansible-tower packages"
    yum:
      name: '*'
      state: latest
      exclude: "{{ excluded_package_list }}"
    when: perform_updates == true

  - name: "Check for reboot hint"
    command: "needs-restarting -r"
    register: reboot_hint
      
  - name: "Debug"
    debug:
      msg: "hint is {{ reboot_hint.stdout }} and rc is {{ reboot_hint.rc }}"
      
  - name: "If no reboot is required, provide status message"
    debug:
      msg: "No reboot required"
    when: reboot_hint.rc == 0

  - name: "If reboot is required, but reboot is set false, provide notice"
    debug:
      msg: "NOTICE!!! REBOOT REQUIRED TO FINISH PATCHING"
    when: ( reboot_hint.rc == 1 ) and ( automatic_reboot == false )
 
  - name: "If reboot is required and reboot flag is set, reboot"
    command: "shutdown -h 30 'Reboot required for patches'"
    when: ( reboot_hint.rc == 1 ) and ( automatic_reboot == true )
...
