---
- hosts: localhost
  vars:
     automatic_reboot: false
     update_ansible_core: true
     excluded_package_list: "ansible-tower*, rabbit*"
     
  tasks:
  - name: "Updating ansible core"
    yum: 
      name: ansible
      state: latest
    when: update_ansible_core

  - name: "Install yum-utils if not already present"
    yum:
      name: yum-utils
      state: latest

  #For extra safety, the excluded package list will be versionlocked using the yum plugin
  #This will prevent extra issues if a manual yum update is run in the future
  - name: "Install yum-plugin-versionlock"
    yum:
      name: yum-plugin-versionlock
      state: latest

  - name: "Add tower packages to versionlock"
    command: "yum versionlock {{ excluded_package_list }}"

  - name: "Update all packages excluding specific ansible-tower packages"
    yum:
      name: '*'
      state: latest
      exclude: "{{ excluded_package_list }}"

  - name: "Check for reboot hint"
    command: "needs-restarting -r ; echo $?"
    register: reboot_hint

  - name: "debug message"
    debug:
      msg: "{{ reboot_hint.stdout }}"
      
  - name: "If no reboot is required, provide status message"
    debug:
      msg: "Patching complete, no reboot required"
    when: reboot_hint.stdout == 0

  - name: "If reboot is required, but reboot is set false, provide notice"
    debug:
      msg: "NOTICE!!! REBOOT REQUIRED TO FINISH PATCHING"
    when: ( reboot_hint.stdout == 1 ) and ( automatic_reboot == "false" )

  - name: "If reboot is required and reboot flag is set, reboot"
    command: "shutdown -h 30 'Reboot required for patches'"
    when: ( reboot_hint.stdout == 1 ) and ( automatic_reboot == "true" )
...
